version: '3'

services:
  db:
    image: postgres
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
      - 5432:5432
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
  server:
    build: ./server
    ports:
      - "8080:8080"
  frontend:
    build: ./client
    ports:
      - "5173:5173"
